### ISSUE TITLE
Shape Issue in MHA in class SkillMhaLayer

### ISSUE THREAD

**Issue by mithunvvv** [LucasCJYSDL/HierAIRL#1]
Hello, 

First of all I want to say thank you for this work! I am very interested in it but running into some issues with incorrect tensor shapes for the MHA layers in the class `SkillMhaLayer` in `HierAIRL_Hopper/utils/MHA_model_util.py` .  In the `forward` method  `tgt` is of shape `2, bs * dim_c, dim_e`  however,  `memory` is of shape `dim_c, bs, dim_e` . According to [pytorch](https://pytorch.org/docs/stable/generated/torch.nn.MultiheadAttention.html), the middle dimension should be the batch size. This mismatch in size is creating an error and causing training to fail. 

According to your [paper](https://arxiv.org/pdf/2210.01969) in equation 13, the query vector is a concatention of the state and option embedding layer and is then passed through a linear layer. However, I don't see that linear layer where the query vector is produced in the code in the `SkillMhaLayer` class. I was wondering if this is causing the issue or if there is another issue causing the shape mismatch before going through the MHA layer. Any help is appreciated. Thank you!

**Comment by LucasCJYSDL** [comment]
Hi, thanks for raising this issue! Have you tried using pytorch 1.6?

**Comment by mithunvvv** [comment]
Thanks for your quick reply, this resolved the issue!

**Comment by LucasCJYSDL** [comment]
Welcome
